met2-19 - pg stat statements data collection pmc
metis-data/metadata-collector pull request #24
Opened 2023-01-29 16:09 UTC by Or92

- to be continued
- improved the query, need to send the payload to the relevant endpoint
- enhanced the select
- renamed the uri
- exported the action added to another file
- closed connection
- fixed api key
- fixed pmc query
- fixed pmc query
- added try catch mechanism

2023-01-29 16:12 UTC, devopsmetis requested changes

2023-01-29 16:12 UTC, devopsmetis commented on client-agent/src/actions.js
> +    console.error(e);
please use logger

2023-01-30 11:34 UTC, gidimetis approved these changes

2023-01-30 11:40 UTC, devopsmetis approved these changes

2023-01-30 11:40 UTC, devopsmetis commented on client-agent/src/actions/stat_statments.js
>          throw e;
Why are you keep throwing this error ?

2023-01-30 11:41 UTC, merged